---
- name: Lighttpd | Certbot install and config
  block:
    - name: Install certbot
      yum:
        name:
          - certbot
        state: "{{ packages_state | default('present') }}"

    - name: Get installed certbot certificates
      shell:
        cmd: "certbot certificates 2>/dev/null | grep 'Certificate Name' | awk -F': ' '{print $2}'"
      register: _installed_letsencrypt_certs
      ignore_errors: "{{ ansible_check_mode }}"

    - debug:
        var: _installed_letsencrypt_certs

    - name: Install certificates
      include_tasks: certbot_run.yml
      when: item not in _installed_letsencrypt_certs
      loop: "{{ letsencrypt_vhosts | selectattr( 'certificates', 'equalto', 'letsencrypt') | map( attribute = 'name' ) | list }}"

  when: lighttpd_vhosts | selectattr( 'certificates', 'equalto', 'letsencrypt') | list | length > 0
