---
# handlers file for letsencrypt-certbot
# - name: Certbot force renew | Stop webservice
#   service:
#     name: "{{ _webservice }}"
#     state: stopped
#   listen: Certbot force renew
#   when:
#     - _webservice is defined
# 
# - name: Certbot force renew | Run
#   command:
#     cmd: >-
#       /usr/bin/certbot renew --force-renewal
#   listen: Certbot force renew
# 
# - name: Certbot force renew | Start webservice
#   service:
#     name: "{{ _webservice }}"
#     state: started
#   listen: Certbot force renew
#   when:
#     - _webservice is defined


#- name: Run deploy hook
#  command:
#    cmd: deploy
#    chdir: /etc/letsenrypt/live
#  environment:
#    RENEWED_LINEAGE:

- name: Run deploy hook
  debug:
    var: _certbot_new_certs
